version: '3'

services:
  app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ".:/app"
    command: "poetry run python app/main.py"
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - SECRET_KEY=secret_key

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5433:5432"
