version: 2.1
orbs:
  sonarcloud: extendaretail/sonarcloud@0.0.2
jobs:
  build:
    docker:
      - image: python:3.11  # You can choose the Python version you need
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: 5432
      SECRET_KEY: "secret_key"
    steps:
      - checkout
      - run:
          name: Get Pipeline Id
          command: |
            echo "This is pipeline ID << pipeline.id >>"
      - run:
          name: Install Dependencies
          command: |
            pip install poetry
            poetry install
      - run:
          name: Run Tests
          command: |
            export POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            export POSTGRES_DB=$POSTGRES_DB
            export POSTGRES_USER=$POSTGRES_USER
            export POSTGRES_HOST=$POSTGRES_HOST
            export POSTGRES_PORT=$POSTGRES_PORT
            export SECRET_KEY=$SECRET_KEY
            poetry run pytest
  install-build-test:
    docker:
      - image: cimg/python:3.11.5-node
    steps:
      - checkout
      - sonarcloud/scan
  compliance-check:
    docker:
      - image: python:3.11
    steps:
      - run:
          name: Compliance Check
          command: |
            echo "This is pipeline ID << pipeline.id >>"
            echo ${CIRCLE_PULL_REQUEST##*/}

workflows:
  build-test:
    jobs:
      - build
      - compliance-check
#      - install-build-test
  compliance:
    jobs:
      - compliance-check
