version: 2.1
jobs:
  build:
    docker:
      - image: python:3.11  # You can choose the Python version you need
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install poetry
            poetry install
      - run:
          name: Run Tests
          command: |
            poetry run pytest
